import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

/**
 * Dev-only. Started from main.tsx when `VITE_MOCK_API=1`.
 *
 * `public/mockServiceWorker.js` is generated by `pnpm msw init public/` and is
 * committed, because the worker script has to be served from the app's origin.
 */
export const worker = setupWorker(...handlers);

export async function startMockApi(): Promise<void> {
  await worker.start({
    serviceWorker: { url: '/mockServiceWorker.js' },
    // Anything the handlers do not cover should reach the network (or fail
    // loudly), not be silently swallowed.
    onUnhandledRequest: 'bypass',
    quiet: false,
  });
}
